"""Synchronous selection and explicit purchase client for observed Wolt hosts."""

from .auth import RefreshTokenCredentials
from .client import WoltClient
from .credentials import SessionCredentials
from .errors import (
    DuplicatePurchaseAttempt,
    HTTPStatusError,
    OrderOutcomeUnknown,
    PurchaseAttemptStoreError,
    PurchaseAuthorizationError,
    PurchasePreparationError,
    RequestFailedError,
    RequestTimeoutError,
    ResponseDecodeError,
    ResponseShapeError,
    SelectionError,
    UnsupportedSelectionError,
    WoltApiError,
    WoltTransportError,
)
from .models import DeliveryTarget, OrderStatus, PaymentMethod, Venue
from .purchase import (
    PurchaseAttemptStore,
    PurchaseAuthorization,
    PurchaseConfirmationSummary,
    PurchaseContext,
    PurchaseLineSummary,
    PurchaseNameSummary,
    PurchaseOptionSummary,
    PurchaseOptionValueSummary,
    PurchaseResult,
    PreparedOrder,
    authorize_prepared_order,
)
from .selection import (
    DeliverySelection,
    ItemSelection,
    OptionSelection,
    OptionValueSelection,
    OrderSelection,
    PostCheckoutConfig,
    QuoteSnapshot,
    SavedBasket,
    VenueCheckoutContext,
    derive_checkout_fields,
)
from .transport import WoltTransport

__all__ = [
    "DeliveryTarget",
    "DeliverySelection",
    "DuplicatePurchaseAttempt",
    "HTTPStatusError",
    "ItemSelection",
    "OptionSelection",
    "OptionValueSelection",
    "OrderOutcomeUnknown",
    "OrderStatus",
    "OrderSelection",
    "PaymentMethod",
    "PostCheckoutConfig",
    "PreparedOrder",
    "PurchaseAttemptStore",
    "PurchaseAttemptStoreError",
    "PurchaseAuthorization",
    "PurchaseAuthorizationError",
    "PurchaseConfirmationSummary",
    "PurchaseContext",
    "PurchaseLineSummary",
    "PurchaseNameSummary",
    "PurchaseOptionSummary",
    "PurchaseOptionValueSummary",
    "PurchasePreparationError",
    "PurchaseResult",
    "QuoteSnapshot",
    "RefreshTokenCredentials",
    "RequestFailedError",
    "RequestTimeoutError",
    "ResponseDecodeError",
    "ResponseShapeError",
    "SavedBasket",
    "SelectionError",
    "SessionCredentials",
    "UnsupportedSelectionError",
    "Venue",
    "VenueCheckoutContext",
    "WoltApiError",
    "WoltClient",
    "WoltTransport",
    "WoltTransportError",
    "authorize_prepared_order",
    "derive_checkout_fields",
]
